window.CivicPulseAnalytics = (function () {
  let charts = {};
  function destroy(key) { if (charts[key]) { charts[key].destroy(); charts[key] = null; } }
  function countBy(items, key) { const counts = {}; items.forEach((item) => { const value = item[key] || "Unspecified"; counts[value] = (counts[value] || 0) + 1; }); return counts; }
  function baseOptions(extra = {}) { return { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } }, ...extra }; }
  function renderCategory(items) { destroy("category"); const counts = countBy(items, "ai_category"); const ctx = document.getElementById("chartCategory"); if (!ctx) return; charts.category = new Chart(ctx, { type: "bar", data: { labels: Object.keys(counts), datasets: [{ data: Object.values(counts), backgroundColor: "#2E6B4C", borderRadius: 2 }] }, options: baseOptions({ indexAxis: "y", scales: { x: { beginAtZero: true, ticks: { precision: 0 } } } }) }); }
  function renderSeverity(items) { destroy("severity"); const order = ["Low", "Medium", "High", "Critical"]; const counts = countBy(items, "ai_severity"); const labels = order.filter((value) => counts[value]); const colors = { Low: "#2E6B4C", Medium: "#B9791F", High: "#A6421F", Critical: "#8C2A2A" }; const ctx = document.getElementById("chartSeverity"); if (!ctx) return; charts.severity = new Chart(ctx, { type: "doughnut", data: { labels, datasets: [{ data: labels.map((label) => counts[label]), backgroundColor: labels.map((label) => colors[label]) }] }, options: baseOptions({ plugins: { legend: { display: true, position: "bottom", labels: { boxWidth: 10, font: { size: 11 } } } } }) }); }
  function renderStatus(items) { destroy("status"); const order = ["Pending", "Acknowledged", "In Progress", "Resolved"]; const counts = countBy(items, "status"); const labels = order.filter((value) => counts[value]).length ? order : Object.keys(counts); const ctx = document.getElementById("chartStatus"); if (!ctx) return; charts.status = new Chart(ctx, { type: "bar", data: { labels, datasets: [{ data: labels.map((label) => counts[label] || 0), backgroundColor: "#B9791F", borderRadius: 2 }] }, options: baseOptions({ scales: { y: { beginAtZero: true, ticks: { precision: 0 } } } }) }); }
  function renderTrend(items) { destroy("trend"); const counts = {}; items.forEach((item) => { if (!item.created_at) return; const day = new Date(item.created_at).toLocaleDateString(); counts[day] = (counts[day] || 0) + 1; }); const days = Object.keys(counts).sort((a, b) => new Date(a) - new Date(b)); const ctx = document.getElementById("chartTrend"); if (!ctx) return; charts.trend = new Chart(ctx, { type: "line", data: { labels: days, datasets: [{ data: days.map((day) => counts[day]), borderColor: "#2E6B4C", backgroundColor: "#E4EFE7", fill: true, tension: 0.25, pointRadius: 3 }] }, options: baseOptions({ scales: { y: { beginAtZero: true, ticks: { precision: 0 } } } }) }); }
  function renderAll(items) { renderCategory(items); renderSeverity(items); renderStatus(items); renderTrend(items); }
  return { renderAll };
})();
